version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network
    command: npm run dev

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myadmin
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-data:/data/db
    command: ["--auth"]
    networks:
      - app-network

  postgres:
    image: postgres:16
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  mongo-data:
  postgres-data:

networks:
  app-network:
    driver: bridge